Restrict FeedItemEventType
lens-protocol/lens-sdk pull request #131
Opened 2023-01-31 18:19 UTC by paulxuca

2023-02-01 16:25 UTC, desfero requested changes
Looks good, just small nitpicks to discuss

2023-02-01 16:25 UTC, desfero commented on packages/react/src/feed/useFeed.ts
> +const mapRestrictEventTypesToLensTypes = (restrictEventTypesTo?: FeedEventItemType[]) => {
nit: wondering if we could get rid of `ifs` at all
```
const SupportedFeedEvenTypesMap: Record<FeedEventItemType, LensFeedEventItemType> = {
  [FeedEventItemType.Comment]: LensFeedEventItemType.Comment,
  [FeedEventItemType.Post]: LensFeedEventItemType.Post,
  [FeedEventItemType.Mirror]: LensFeedEventItemType.Mirror,
  [FeedEventItemType.CollectComment]: LensFeedEventItemType.CollectComment,
  [FeedEventItemType.CollectPost]: LensFeedEventItemType.CollectPost,
};

const mapRestrictEventTypesToLensTypes = (restrictEventTypesTo?: FeedEventItemType[]) => {
  return restrictEventTypesTo?.map((type) =>
    nonNullable(SupportedFeedEvenTypesMap[type], "Can't map the feed even type"),
  );
};
```

2023-02-01 16:25 UTC, desfero commented on packages/react/src/feed/FeedEventItemType.ts
> +export enum FeedEventItemType {
nit: just thinking, maybe it's not the responsibility of `@lens-protocol/react` to protect which `FeedEvenItemType` is supported but rather `@lens-protocol/react` should overwrite the `useFeedHook` to guide what can be used?

2023-02-01 16:46 UTC, desfero commented on packages/react/src/feed/FeedEventItemType.ts
> +export enum FeedEventItemType {
after thinking a little bit more it seems not worth the effort to add more complexity to the `api-bindings`

2023-02-06 10:02 UTC, krzysu approved these changes

2023-02-06 15:12 UTC, desfero approved these changes

2023-02-06 15:14 UTC, merged