feat: remove `hasOptimisticCollectedByMe` and enhance `hasCollectedByMe`
lens-protocol/lens-sdk pull request #291
Opened 2023-04-12 07:49 UTC by krzysu

2023-04-12 11:40 UTC, krzysu commented on packages/api-bindings/src/graphql/client.graphql
> +  @deprecated use hasCollectedByMe instead
this is not added to generated .ts files, so end-user won't see them in their IDE.

2023-04-12 13:34 UTC, cesarenaldi commented on packages/api-bindings/src/apollo/cache/publicationTypePolicy.ts
> +    publicationId,
Similarly to what we did for `recentTransactionsVar` I think the `activeProfileIdentifierVar` should be moved in `@lens-protocol/api-bindings` and then imported and used by the `ActiveProfilePresenter` and `useActiveProfileIdentifierVar` in the `@lens-protocol/react` package. Once you have the `activeProfileIdentifierVar` in this package you can simply import it and use it here.

2023-04-13 12:20 UTC, krzysu commented on packages/api-bindings/src/apollo/cache/publicationTypePolicy.ts
> +    publicationId,
done, I guess it's ready for review now

2023-04-17 10:46 UTC, cesarenaldi requested changes
Neat, can you please add a changeset?

2023-04-17 12:27 UTC, cesarenaldi commented on .changeset/large-mugs-fetch.md
> +"@lens-protocol/react": minor
Sorry, one last thing, can you please add `@lens-protocol/react-web` here? We need to update the deps with the updated `@lens-protocol/react`.
```suggestion
"@lens-protocol/react": minor
"@lens-protocol/react-web": minor
```

2023-04-18 15:42 UTC, merged