feat: add `useReportPublication` hook (T-2513)
lens-protocol/lens-sdk pull request #80
Opened 2023-01-13 12:18 UTC by krzysu

add `useReportPublication` hook

2023-01-18 10:28 UTC, desfero requested changes

2023-01-18 10:28 UTC, desfero commented on packages/react/src/publication/useReaction.ts
> +      setError(null);
👍

2023-01-18 10:28 UTC, desfero commented on packages/react/src/publication/adapters/ReportPublicationGateway.ts
> +export class ReportPublicationGateway implements IReportPublicationGateway {
Would be good to have tests for the gateway

2023-01-18 10:28 UTC, desfero commented on packages/react/src/publication/adapters/ReportPublicationPresenter.ts
> +export class ReportPublicationPresenter implements IReportPublicationPresenter {
Could we reuse our `PromiseResultPresenter` presenter and avoid having `ReportPublicationPresenter` at all?

2023-01-19 08:37 UTC, krzysu commented on .changeset/calm-rockets-sit.md
> +"@lens-protocol/domain": minor
thanks for the explanation! I will fix it

2023-01-19 09:02 UTC, desfero approved these changes

2023-01-19 09:03 UTC, merged