Lists all profiles owned by a given address
lens-protocol/lens-sdk pull request #84
Opened 2023-01-16 11:43 UTC by cesarenaldi

This is part 1 of 2.

The next PR will add an hook to change the active profile. I will consider if merge the 2 into 1 single hook or keep them separate and provide a tiny wrapper for "profile switchers" UIs convenience.

2023-01-16 12:13 UTC, desfero approved these changes

2023-01-16 12:13 UTC, desfero commented on examples/web-wagmi/src/profiles/components/ProfileCard.tsx
> +      {profile?.name && <p>Name: {profile?.name}</p>}
👍

2023-01-16 12:13 UTC, desfero commented on examples/web-wagmi/src/profiles/components/ProfileCard.tsx
> +      {profile?.name && <p>Name: {profile?.name}</p>}
nit: no need to use elvis operator again

2023-01-16 12:14 UTC, desfero requested changes

2023-01-16 19:42 UTC, cesarenaldi commented on packages/react/src/profile/useProfilesOwnedBy.ts
> +export function useProfilesOwnedBy({
Added

2023-01-17 09:01 UTC, desfero approved these changes

2023-01-17 13:52 UTC, merged